### ISSUE TITLE
GitHub Actionsでエラーが出ている

### ISSUE THREAD

**Issue by tyokinuhata** [uyupun/official#257]
該当のアクション

- https://github.com/uyupun/official/actions/runs/5518088512/jobs/10061576085
- https://github.com/uyupun/official/actions/runs/5518088577/jobs/10061576450

**Comment by tyokinuhata** [comment]
- publish-storybookのエラーログ

```
Push the commit or tag
  /usr/bin/git push origin gh-pages
  remote: Permission to uyupun/official.git denied to github-actions[bot].
  fatal: unable to access 'https://github.com/uyupun/official.git/': The requested URL returned error: 403
  Error: Action failed with "The process '/usr/bin/git' failed with exit code 128"
```

**Comment by tyokinuhata** [comment]
- notify-storybook-url > Comment on PRのエラーログ

```
Run actions/github-script@v6
Error: Input required and not supplied: github-token
    at Object.getInput (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:212:15)
    at main (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:152[19](https://github.com/uyupun/official/actions/runs/5518088577/jobs/10061576450#step:3:20):24)
    at /home/runner/work/_actions/actions/github-script/v6/dist/index.js:15[21](https://github.com/uyupun/official/actions/runs/5518088577/jobs/10061576450#step:3:22)7:1
    at /home/runner/work/_actions/actions/github-script/v6/dist/index.js:15268:3
    at Object.<anonymous> (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:15271:12)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:8[22](https://github.com/uyupun/official/actions/runs/5518088577/jobs/10061576450#step:3:23):12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
Error: Unhandled error: Error: Input required and not supplied: github-token
```

**Comment by tyokinuhata** [comment]
検討項目

- 上記２つのエラーの根本解決
- dependabotが作成するPRに必要なワークフローの洗い出し

**Comment by tyokinuhata** [comment]
# notify-storybook-url > Comment on PRのエラーの原因

- @tyokinuhata や @takashi0602 はuyupunのGithubオーガナイゼーションに所属しているユーザである
- それに対して、DependabotはuyupunのGitHubオーガナイゼーションに所属しないユーザである
- GitHubオーガナイゼーションに所属しないユーザからのPRはアップストリームのリポジトリをフォークし、そこから送られてくる
- そして、そのような外部から送られてくるPRは`pull_request`イベントを実行する権限を持たない

**Comment by tyokinuhata** [comment]
# notify-storybook-url > Comment on PRのエラー解決策

- 該当ワークフローには特にPRに含まれるコードに基づいて何かを実行するようなフローは含まれていない
- そのため、外部からのPRであってもこのワークフローは実行してセキュリティリスクはないと考える
- `pull_request`イベントから`pull_request_target`イベントに変更することで、外部からのPRであっても適切な権限が付与されるはず

**Comment by tyokinuhata** [comment]
# 最終的にどうするか

- 大前提として、このリポジトリは基本的にうゆぷんのメンバーしか触らないというのがある
- Storybook/Lighthouseのデプロイはセキュリティリスクを考え、GitHubオーガナイゼーションに所属するメンバーにのみ許可をする現行の方式のままにする
- GitHub Pagesのデプロイ先URLの通知はセキュリティリスクなく行うことは可能だが、そもそもデプロイされないため通知する必要がないため、GitHubオーガナイゼーションに所属するメンバーにのみ許可をする現行の方式のままにする
- 仮にGitHubオーガナイゼーション外のユーザからのPRが送られてきた場合でも、Chromaticでコンポーネントの差分は見れるはず(DependabotからのPRでは無効化しているため未検証)
-
